[theme]
base = "light"
primaryColor = "#2196F3"
backgroundColor = "#DDF3FF"
secondaryBackgroundColor = "#CFEFFF"
textColor = "#17202A"
font = "sans serif"

[theme.light]
base = "light"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6F8"
textColor = "#17202A"
borderColor = "#D9DEE3"

[theme.dark]
base = "dark"
backgroundColor = "#0B1118"
secondaryBackgroundColor = "#111923"
textColor = "#EDF2F7"
borderColor = "#293540"
